[project]
name = "mysklearn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.9.0"
dependencies = [
    "xgboost>=1.0,<3.0",
    "numpy~=1.24.1",
    "scipy~=1.8.0",
    "sagemaker-inference>=1.10.1",
]
